### PR TITLE
[PULL REQUEST] Revise English Translation

### PR DESCRIPTION
**Pull request by kiraio-moe**
This is WIP PR, please don't merge it yet. I still revising the Commands explanation.
Well, if you want to merge it now, it's not a problem.

### CODE REVIEW

**Comment by hsdk123** [comment]
Looks great!
@TakashiYukihara could you take a quick look?

**Review by TakashiYukihara — APPROVED** [review]

**Comment by hsdk123** [comment]
Looking good to me:

image

**Comment by kiraio-moe** [comment]
> Looking good to me:
> 
> image

Welp, just need some salt to the UI/UX.
However, glad you liked the PR. If there's something needs to be edited, don't hesitate to ping me :)

Is the Wiki page (https://wikiwiki.jp/lightvn/) support multi-languages like Wikipedia does?

**Comment by hsdk123** [comment]
> Is the Wiki page (https://wikiwiki.jp/lightvn/) support multi-languages like Wikipedia does

Sadly not, would be a todo item for the future!

**Comment by kiraio-moe** [comment]
> Sadly not, would be a todo item for the future!

That's sad. Well, for now let's complete translating `Commands` details first!

**Pull request merged**
